server:
  port: 9527
  
spring:
  application:
    name: microserviceclouds-zuul-gateway

eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
       
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
    
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifacId$
  build.version: 0.0.1-SNAPSHOT
  
zuul:
  prefix: /atguigu #前缀
  ignored-services:
  -  "*"
# ignored-services: microserviceclouds-dept 禁调
  routes:
    mydept.serviceId: microserviceclouds-dept
    mydept.path: /mydept/**
  